version: 2

project_name: graphql-cli

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: graphql-cli
    main: .
    binary: graphql-cli
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  draft: true

archives:
  - id: archive
    ids: [graphql-cli]
    formats: [zip]
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
